//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruApp.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoruDataEntities1 : DbContext
    {
        public SoruDataEntities1()
            : base("name=SoruDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Konu> tbl_Konu { get; set; }
        public virtual DbSet<tbl_Kullanıcı> tbl_Kullanıcı { get; set; }
        public virtual DbSet<tbl_Ogrenci> tbl_Ogrenci { get; set; }
        public virtual DbSet<tbl_Ogretmen> tbl_Ogretmen { get; set; }
        public virtual DbSet<tbl_Sınav> tbl_Sınav { get; set; }
        public virtual DbSet<tbl_Soruu> tbl_Soruu { get; set; }
        public virtual DbSet<tbl_KonuBasari> tbl_KonuBasari { get; set; }
    }
}
