//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruApp.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanıcı
    {
        public string kullanıcı_ad { get; set; }
        public string kullanıcı_sifre { get; set; }
        public int kullanıcı_ıd { get; set; }
    
        public virtual tbl_Ogrenci tbl_Ogrenci { get; set; }
        public virtual tbl_Ogretmen tbl_Ogretmen { get; set; }
    }
}
