//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruApp.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KonuBasari
    {
        public int sınav_ıd { get; set; }
        public int konu_ıd { get; set; }
        public Nullable<int> basarili_mi { get; set; }
    
        public virtual tbl_Konu tbl_Konu { get; set; }
        public virtual tbl_Sınav tbl_Sınav { get; set; }
    }
}
