//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruApp.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sınav
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sınav()
        {
            this.tbl_KonuBasari = new HashSet<tbl_KonuBasari>();
        }
    
        public int sınav_ıd { get; set; }
        public Nullable<int> ogrenci_ıd { get; set; }
        public Nullable<int> dogru_sayisi { get; set; }
    
        public virtual tbl_Ogrenci tbl_Ogrenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KonuBasari> tbl_KonuBasari { get; set; }
    }
}
